name: Bygg og push docker image til team tilbake GAR
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and push Docker container 🐳
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: yarn
          registry-url: "https://npm.pkg.github.com"

      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tilbake
          tag: latest
